# Generated by Django 2.2.1 on 2019-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20190916_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heat',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='article',
            name='recommend',
            field=models.IntegerField(default=0, verbose_name='推荐'),
        ),
    ]
